apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: inventory-cpu-stress
  namespace: ai-sre
spec:
  mode: one
  selector:
    namespaces:
      - ai-sre
    labelSelectors:
      app: inventory-service
  stressors:
    cpu:
      workers: 2
      load: 80
  duration: "30s"