apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: order-network-delay
  namespace: ai-sre
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - ai-sre
    labelSelectors:
      app: order-service
  delay:
    latency: "1000ms"
    correlation: "100"
    jitter: "0ms"
  duration: "30s"